ASIMS/ASIMS/Controllers/UserAccountController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ASIMS.Models;
using ASIMS.Models.Method;
using ASIMS.Models.Methods;

namespace ASIMS.Controllers
{
    public class UserAccountController : Controller
    {
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Login(string username,string password)
        {
            UserInforManagement function = new UserInforManagement();
            bool isTure = function.Login(username, password);
            if (!isTure)
            {
                var message = "登录失败，请核对账号和密码！";
                ViewBag.message = message;
                return View();
            }
            else
                return RedirectToAction("Index", "Home");

        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ASIMS/ASIMS/Views/UserAccount/Login.cshtml
@{
    ViewData["Title"] = "Login";
    Layout = null;
}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//ZH" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>Aoki-login</title>
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <link rel="stylesheet" href="css/style.css" />
</head>

<body>
     
    <div class="login-container">
        <h1>ASIMS</h1>

        <div class="connect">
            <p>Welcome</p>
        </div>

        <form action="@Url.Action("Login","UserAccount")" method="post" id="loginForm">
            <div>
                <input type="text" name="username" class="phone" placeholder="手机号" autocomplete="off" />
            </div>
            <div>
                <input type="password" name="password" class="password" placeholder="密码" oncontextmenu="return false" onpaste="return false" />
            </div>
            <button id="submit" type="submit">登 录</button>
        </form>
        <a href="register.html">
            <button type="button" class="register-tis">还有没有账号？</button>
        </a>
    </div>
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/common.js"></script>
    <!--背景图片自动更换-->
    <script src="~/js/supersized.3.2.7.min.js"></script>
    <script src="~/js/supersized-init.js"></script>
    <!--表单验证-->
    <script src="~/js/jquery.validate.min.js?var1.14.0"></script>
    
</body>
</html>
<script>
    function check() {
        var warning = " @Html.Raw(ViewBag.message)";
        if (warning.length>2) {
            alert(warning);
        }
    }
    window.onload = check;
</script>